travis:
  secure:
    BINSTAR_TOKEN: do8B1H8JJk8a1Ofv9vNILp2tQY2h6YjbQUwXrpwimGcj8uPIfrVyXKGg5uv1hkZe0hYNV6QWvumg5g8f6X2DvFhfHW3DXIcMj/jwWM/JuFZVZMffEonJxcgVQWWDN7R/hbeoL1XzVn34GX+GsNm0lZjlaShvk6h9j3WcpQQPmU2G3igyRKB0RPnxWiVimPwyOIRC/xwCMD1exWzDYkFH0+7vXgS0Htp7N6IOmfSNL2bkySaNINoZzqiiOD8ZQxe6wZYNhTe3Db85z4gvkapXo296YQLTBhHDZ/jZyhNGN/Rk5oBUTATf4jzxw7O/9UNaPagr24IemjYWDJgWT/yHzTmgsDMqo+3QgKDX561irU2Up2FjjXTnqzZ7Nokz2/cvaV5Ndss7i9QJwsopsq8gw1caIG5nU3rsp7wp8CK9EsSW+UUptOYoQ12LWsvpJPV/HcRLXzM5zDfPrvLoA3QlgtbyLZ5m44PSRneAokJDVkvC9rBMdqMjJHbe4HtYu29N+BSH5gioPDQ+K1Bq3dcAjT7GlG1DOcKOz+AHVDLFxeCuM3eCmft1UM6MBV4vL9O6g+ToXfBfrtBZgy5ne9McE79sz32gkQhnripitQPT1TrDPqx1/+TMPwxULOvYOhapE9hGNW0RJf2bHp+c+XchemGadKzzzxP8FgxJbQjA2B8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
