travis:
  secure:
    BINSTAR_TOKEN: TNcc3EWD+NMCdhbmE6v3JveSug42T0mCxOS0MIEOnWGChsNsrOtBdekjKetA3uFsVaeJQQNfjJxuKfmFZVncmAwhKL7atNSxbU8NTDrTr67pjqOSNl472ch4pdjy9YaqVnpR2bM1/rn6TYMWo/hT0HSNUlrte1ZLACBfGq0YOHqZtlTH8dlY9v01JrAd4yKgDqiPx2NZ1tzGGghg3EklRbgINwDldMW3cRsJbBaw3r8SUiRRJeVv3uWh0ZXw6roMDBlJGIz2bKJOzEKmKcz/Ei2DwpeZDDOy0mmgqc9GMXyph5jstMQ4d35DFtzM3wdBOk/DbWVn3kIwBpchx3j60TXp2voVIDxBfitsZ0et+RFW5DccZ0Ch+NAJqN+qhcKL8J4oUC959tunRFFKqonyMUwEr3J1qy/IWxt8q7vn2nxjQeuOaoMLAeOdv8F4ACUlsufuIJjrbKXAz06IHPx9dRmA81koohk5Ub4wCjLZUNILFmt5Z4TeL71rRW09lziG4pM7VLdQDGL0Bn+Gjyteh9Pn0mf4FnqLgqS1XBM5/J65mCokEar12IJDwiQhFndj0oDwqwC3ZxAt+L51C9zXMhETyJcn7It3AEzbr0wL6i3iOWfSAktnrqBF5MpxzTCEqaq9f3eDQ5XbyO9by+FVVIqk9PJPpRhUe3KgnKwo/2c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
